services:
  db:
    image: mysql/mysql-server:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_TCP_PORT: ${PORT}
    ports:
      - 3307:3307
    expose:
      - 3307
    volumes:
      - ./database/data:/var/lib/mysql
    networks:
      - IWD
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env.production
    depends_on:
      - api
    networks:
      - IWD

  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=${PORT}
      - DATABASE_USER=${USER}
      - DATABASE_PASSWORD=${PASSWORD}
      - DATABASE_NAME=${DATABASE}
      - FRONTEND_PORT=${FRONTEND_PORT}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - IWD

networks:
  IWD:
    driver: bridge