export const data = [
    {category:"Mark", value: 90},
    {category:"Robert", value: 12},
    {category:"Emily", value: 34},
    {category:"Marion", value: 53},
    {category:"Nicolas", value: 98},
    {category:"Mel", value: 23},
    {category:"Gabriel", value: 18},
    {category:"Jean", value: 104},
    {category:"Sophie", value: 14},
    {category:"Leane", value: 74},
    {category:"Melanie", value: 72},
    {category:"Tibo", value: 23},
    {category:"Remi", value: 124},
    {category:"Balkis", value: 23},
    {category:"Nina", value: 104},
    {category:"Lucas", value: 94},
    {category:"Paul", value: 2},
]
